# Generated by Django 3.2.7 on 2021-10-02 09:55

from django.db import migrations
import django_measurement.models
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='volume',
            field=django_measurement.models.MeasurementField(default=0.0, measurement=measurement.measures.volume.Volume),
        ),
    ]
