# Generated by Django 3.2.7 on 2021-10-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_beer_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='volume',
        ),
    ]
