# Generated by Django 4.0 on 2021-12-31 11:33

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(default='drink.png', upload_to=app.models.upload_to),
        ),
    ]
